#!/bin/bash
#

function find_base_dir {
    local real_path=$(python -c "import os; print(os.path.realpath('$0'))")
    local dir_name="$(dirname "$real_path")"
    if [[ ${dir_name} == "/usr/bin" ]]; then
        BASEDIR=/usr/share/kolla
    elif [[ ${dir_name} == "usr/local/bin" ]]; then
        BASEDIR=/usr/local/share/kolla
    else
        BASEDIR="$(dirname ${dir_name})"
    fi
}

function process_cmd {
    echo "$ACTION : $CMD"
}

function usage {
    cat << EOF
Usage: $0 COMMAND [options]

Options:
    --inventory, -i <inventory_path>
    --playbook, -p <playbook_path>
    --help, -h
    --extra, -e <ansible variables>
    --graceful
    --overlap-replace

Commands:
    deploy
    upgrade
EOF
}

SHORT_OPTS="hi:p:e:"
LONG_OPTS="help,inventory:,playbook:,extra:,graceful,overlap-replace"
ARGS=$(getopt -o "${SHORT_OPTS}" -l "${LONG_OPTS}" --name "$0" -- "$@") || { usage >&2; exit 2; }$

eval set -- "$ARGS"

find_base_dir

INVENTORY="${BASEDIR}/ansible/inventory/all-in-one"
PLAYBOOL="${BASEDIR}/ansible/site.yml"
VERBOSITY=
EXTRA_OPTS=

while [ "$#" -gt 0 ]; do
    case "$1" in

    (--inventory|-i)
        INVENTORY="$2"
        shift 2
        ;;
    (--playbook|-p)
        PLAYBOOK="$2"
        shift 2
        ;;
    (--extra|-e)
        EXTRA_OPTS="$EXTRA_OPTS -e $2"
        shift 2
        ;;
    (--graceful)
        EXTRA_OPTS="$EXTRA_OPTS -e graceful=True"
        shift 2
        ;;
    (--overlap-replace)
        EXTRA_OPTS="$EXTRA_OPTS -e overlap_replace=True"
        shift 2
        ;;
    (help|-h)
        usage
        shift
        exit 0
        ;;
    (--)
        shift
        ;;
    (*)
        echo "error"
        exit 3
        ;;
    esac
done

case "$1" in

(deploy)
    ACTION="Deploy Kolla containers"
    EXTRA_OPTS="$EXTRA_OPTS -e action=deploy" 
    ;;
(upgrade)
    ACTION="Upgrade Kolla containers"
    EXTRA_OPTS="$EXTRA_OPTS -e action=upgrade" 
    ;;
(*)
    usage
    exit 0
    ;;
esac

CMD="ansible-playbook -i $INVENTORY $EXTRA_OPTS $PLAYBOOK"
process_cmd
